version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    links:  # link from another container
      - db
    depends_on:
      - db

  db:
    image: postgres:11.5
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data # it will save state
    ports:
      - 5432:5432

volumes:
  pgdata:
