version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: "python manage.py runserver 0.0.0.0:8080"
    links:  # link from another container
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data # it will save state
    ports:
      - 5432:5432

volumes:
  pgdata:
